version: '3.8'
services:
        webserver:
                build:
                        context: .
                        dockerfile: ./webserver/Dockerfile
                image: web_serve_${POSTFIX}
                container_name: WEB_${POSTFIX}
                stdin_open: true
                command: python3 /webserver/server.py 
                volumes:
                        - ${STORAGE}:/mnt/data
                restart: always
                environment:
                        - PYTHONUNBUFFERED=1
        nginx:
                build:
                        context: ./nginx
                        dockerfile: ./Dockerfile
                image: nginx_serve_${POSTFIX}
                container_name: NGX_${POSTFIX}
                restart: always
                volumes:
                        - ${STORAGE}:/mnt/data
                ports:
                        - ${NGX_PORT}:80
                        - 7037:80
                links:
                        - webserver
                        - infer
        infer:
                build:
                        context: .
                        dockerfile: ./infer/Dockerfile
                image: infer_serve_${POSTFIX}
                container_name: INFER_${POSTFIX}
                stdin_open: true
                command: python3 /infer/server.py # todo: args
                volumes:
                        - ${STORAGE}:/mnt/data
                        - ${STORAGE_TRT}:/mnt/trt
                restart: always
                environment:
                        - PYTHONUNBUFFERED=1
                deploy:
                  resources:
                    reservations:
                      devices:
                        - driver: nvidia
                          device_ids: ["2"]
                          capabilities: [gpu]
        infer_cpp:
                build:
                        context: .
                        dockerfile: ./infer_cpp/Dockerfile
                image: infer_cpp_serve_${POSTFIX}
                container_name: INFER_CPP_${POSTFIX}
                stdin_open: true
                  #command: python3 /infer/server.py # todo: args
                volumes:
                        - ${STORAGE}:/data
                restart: always
                environment:
                        - PYTHONUNBUFFERED=1
                deploy:
                  resources:
                    reservations:
                      devices:
                        - driver: nvidia
                          device_ids: ["3"]
                          capabilities: [gpu]
        infer_cpp_httplib:
                build:
                        context: .
                        dockerfile: ./infer_cpp_httplib/Dockerfile
                image: infer_cpp_httplib_serve_${POSTFIX}
                container_name: INFER_CPP_HTTPLIB_${POSTFIX}
                stdin_open: true
                  #command: python3 /infer/server.py # todo: args
                volumes:
                        - ${STORAGE}:/data
                restart: always
                environment:
                        - PYTHONUNBUFFERED=1
                deploy:
                  resources:
                    reservations:
                      devices:
                        - driver: nvidia
                          device_ids: ["3"]
                          capabilities: [gpu]
